name: Build and Test External
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name != 'develop' && github.ref || github.run_id }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  determine-affected:
    name: "Turbo Affected"
    uses: ./.github/workflows/turbo-affected-reusable.yml
    with:
      head_branch: ${{ github.event.pull_request.head.ref || github.event.merge_group.head_ref }}
      base_branch: ${{ github.event.pull_request.base.ref || github.event.merge_group.base_ref }}

  # External from Fork branches
  build-desktop-external:
    name: "[External] Build Desktop"
    needs: determine-affected
    if: ${{contains(needs.determine-affected.outputs.paths, 'ledger-live-desktop') && github.event.pull_request.head.repo.full_name != github.repository }}
    uses: ./.github/workflows/build-desktop-external-reusable.yml

  test-desktop-external:
    name: "[External] Test Desktop"
    needs: determine-affected
    if: ${{contains(needs.determine-affected.outputs.paths, 'ledger-live-desktop') && github.event.pull_request.head.repo.full_name != github.repository }}
    uses: ./.github/workflows/test-desktop-external-reusable.yml

  build-mobile-external:
    name: "[External] Build Mobile"
    needs: determine-affected
    if: ${{contains(needs.determine-affected.outputs.paths, 'ledger-live-mobile') && github.event.pull_request.head.repo.full_name != github.repository}}
    uses: ./.github/workflows/build-mobile-external-reusable.yml

  # Final Check required
  ok:
    name: "OK"
    needs:
      - build-desktop-external
      - test-desktop-external
      - build-mobile-external
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - name: Compute info
        id: info
        if: always()
        run: |
          failure=false
          check () {
            local result=$1
            if [ "$result" != "success" ] && [ "$result" != "skipped" ]; then
              failure=true
            fi
          }
          check ${{needs.build-desktop-external.result}}
          check ${{needs.test-desktop-external.result}}
          check ${{needs.build-mobile-external.result}}
          if [ "$failure" = "true" ]; then
            echo "failure=true" >> $GITHUB_OUTPUT
          else
            echo "success=true" >> $GITHUB_OUTPUT
          fi
      - name: It's not fine
        if: steps.info.outputs.failure == 'true'
        run: exit 1
      - name: It's fine
        if: steps.info.outputs.success == 'true'
        run: echo Ok
